# Generated by Django 4.2.7 on 2024-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0002_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
