# Generated by Django 4.2.7 on 2024-01-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aura', '0003_meeting_meetingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
