# Generated by Django 4.2.7 on 2024-01-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_psychiatrist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrator', 'Administrator'), ('Client', 'Client'), ('psychiatrist', 'psychiatrist')], default='Client', max_length=17, verbose_name='Role'),
        ),
    ]
